title: souce code webgl
description: <!doctype html>
template:
  repo: souce-code-webgl-template
  name: souce-code-webgl
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
